# Generated by Django 3.0.7 on 2020-06-30 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('legal_name', models.CharField(max_length=127)),
                ('phone', models.CharField(default='000.000.0000', max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=80)),
                ('rollnumber', models.IntegerField()),
                ('member_score', models.IntegerField()),
                ('inactive_flag', models.BooleanField()),
                ('abroad_flag', models.BooleanField()),
                ('present', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
