# Generated by Django 3.0.7 on 2020-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_members_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
