# Generated by Django 3.0.7 on 2020-07-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200712_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='profile',
            new_name='avatar',
        ),
    ]
