# Generated by Django 3.0.7 on 2020-07-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200712_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='avatar',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/images/'),
        ),
        migrations.CreateModel(
            name='SoberBros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sb_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_1', to='dashboard.Members')),
                ('sb_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_2', to='dashboard.Members')),
                ('sb_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_3', to='dashboard.Members')),
                ('sb_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_4', to='dashboard.Members')),
                ('sb_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_5', to='dashboard.Members')),
            ],
        ),
    ]
