# Generated by Django 3.0.7 on 2020-07-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200719_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoberBroSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('open_to_chapter_date', models.DateField()),
                ('open_to_chapter_time', models.TimeField()),
                ('lock_sheet', models.DateTimeField()),
                ('name', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
    ]
