# Generated by Django 3.0.7 on 2020-07-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_soberbrosheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='avatar',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/UserMedia/'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='end_time',
            field=models.TimeField(blank=True, default='23:59:59'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='sb_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_1', to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='sb_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_2', to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='sb_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_3', to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='sb_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_4', to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='sb_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sb_5', to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='soberbros',
            name='start_time',
            field=models.TimeField(blank=True, default='08:00:00'),
        ),
    ]
